api:
  base-path: /api/v1
  provider:
    resource:
      base-uri: http://localhost:8181
      endpoint: /api/v1/resource

app:
  allowed-group: "IT"
  version:
    ios: "1.2.1"
    andriod: "1.2.1"

server:
  port: 8088

azure:
  activedirectory:
    client-id: 077eb991-1556-481b-9145-26ded6919fbf
    client-secret: A2i7Q~rIzmbyuSgq-Q4iM55R.kfklTvpIDdNE
    app-id-uri: api://077eb991-1556-481b-9145-26ded6919fbf/web
    tenant-id: a42e43e2-c7b8-499c-89a6-4b9bac2d5a6e
    authorization-clients:
      graph:
        scopes:
          - https://graph.microsoft.com/User.Read
      testco-res:
        scopes:
          - api://testco-res/File.Upload
      testco-webapp:
        scopes:
          - api://testco-webapp/Consumer.read