api:
  base-path: /api/v1


provider:
  apigee:
    base-uri: http://localhost:8088
    verify: /api/v1/verify
    file-upload: /api/v1/file-upload


app:
  allowed-group: "IT"
  version:
    ios: '1.2.1, 1.2.3, 1.2.4'
    android: '1.2.1, 1.2.3, 1.2.4'

apigee:
  upload-endpoint: /api/v1/file-upload
  verify-endpoint: /api/v1/verify
  client-id: testco-res

server:
  port: 8088

azure:
  activedirectory:
    client-id: 077eb991-1556-481b-9145-26ded6919fbf
    client-secret: syp8Q~KKkb2-.3FDpeXYf4KeBLyLU5UstA9EubO. #TODO: Store secrets in VAULT
    app-id-uri: api://077eb991-1556-481b-9145-26ded6919fbf/web
    tenant-id: a42e43e2-c7b8-499c-89a6-4b9bac2d5a6e
    authorization-clients:
      graph:
        scopes:
          - https://graph.microsoft.com/User.Read
      testco-res:
        scopes:
          - api://testco-res/File.Upload
      testco-webapp:
        scopes:
          - api://testco-webapp/Consumer.read
logging:
  level:
    org:
      springframework:
        security: TRACE
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
    com:
      azure:
        spring: TRACE