management:
  endpoints:
    web:
      exposure:
        exclude: ""
        include: "health"
      base-path: /

spring:
  profiles:
    active: dev


application:
  version:
    ios: "2.1.3"
    android: "2.1.3"
logging:
  level:
    org:
      springframework:
        security: DEBUG
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
    com:
      azure:
        spring: TRACE