api:
  base-path: /api/v1
  provider:
    resource:
      base-uri: https://testco-res.azurewebsites.net
      endpoint: /api/v1/resource

app:
  allowed-group: "IT"
  version:
    ios: "1.2.1"
    andriod: "1.2.1"

apigee:
  upload-endpoint: /api/v1/file-upload
  verify-endpoint: /api/v1/verify
  client-id: testco-res

azure:
  client-id: 077eb991-1556-481b-9145-26ded6919fbf
  client-secret: syp8Q~KKkb2-.3FDpeXYf4KeBLyLU5UstA9EubO. #TODO: Store secrets in VAULT
  app-id-uri: api://077eb991-1556-481b-9145-26ded6919fbf/web
  tenant-id: a42e43e2-c7b8-499c-89a6-4b9bac2d5a6e

logging:
  level:
    org:
      springframework:
        security: TRACE
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
    com:
      azure:
        spring: TRACE