management:
  endpoints:
    web:
      exposure:
        exclude: ""
        include: "health"
      base-path: /

spring:
  profiles:
    active: local

logging:
  level:
    org:
      springframework:
        security: TRACE
        web:
          filter:
            CommonsRequestLoggingFilter: TRACE
    com:
      azure:
        spring: TRACE