openapi: 3.0.3
info:
  title: Intune Adapter
  description: Web application that will serve as verification steps using Azrure AD
  version: 1.0.0
servers:
  - url:  https://testco-app.azurewebsites.net

tags:
  - name: Verify
    description: Endpoint for verifying client
  - name: Upload file
    description: Endpoint for checking / receiveing of payload sent by the client

paths:
  /intune/verify:
    get:
      tags:
      - Verify
      summary: "Verify token provided by the client"
      operationId: "verify"

      requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppInformation'

      security:
        - bearerAuth: [ ]

      responses:
        200:
          $ref: '#/components/responses/Accepted'
        400:
          $ref: '#/components/responses/BadRequest'
        402:
          $ref: '#/components/responses/NotSupported'
        401:
          $ref: '#/components/responses/AccessDenied'
        403:
          $ref: '#/components/responses/ForbiddenAccess'
        500:
          $ref: '#/components/responses/InternalError'

  /intune/upload-file:
    post:
      tags:
        - Upload file
      summary: "Receive uploaded file from client"
      description: "Check the validity of the token and verify the uploaded file"
      operationId: "uploadFile"

      security:
        - bearerAuth: []

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FileUpload'

      responses:
        200:
          $ref: '#/components/responses/Accepted'
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/AccessDenied'
        403:
          $ref: '#/components/responses/ForbiddenAccess'
        500:
          $ref: '#/components/responses/InternalError'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    Accepted:
      description: "Access granted."
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Accepted'

    BadRequest:
      description: "Request error."
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BadRequest'

    AccessDenied:
      description: "Access denied."
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AccessDenied'

    ForbiddenAccess:
      description: "Access forbidden. Not enough rights."
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Forbidden'

    InternalError:
      description: "Internal Error occured."
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InternalError'

  schemas:
    AppInformation:
      type: object
      description: "Information about request origin."
      required:
        - appOs
        - appVersion
      properties:
        appOs:
          type: string
          example: "iOs"
        appVersion:
          type: string
          example: "2.0.0"

    FileUpload:
      type: object
      description: "Uploaded file"
      required:
        - file
        - metadata
      properties:
        file:
          type: string
          example: "byte64encodedString"
        metadata:
          $ref: '#/components/schemas/Metadata'
    Metadata:
      type: object
      description: "Information about the file sent"
      properties:
        name:
          type: string
        copyOfOriginal:
          type: boolean

    Accepted:
      type: object
      description: "Accepted"
      properties:
          status:
            type: integer
            example: 200
            default: 200
          title:
            type: string
            example: "Access granted"
            default: "Access granted"
    BadRequest:
      type: object
      description: "Something wrong with the request."
      properties:
        status:
          type: integer
          default: 400
        title:
          type: string
          default: "Bad Request."
    AccessDenied:
      type: object
      description: "Access denied."
      properties:
        status:
          type: integer
          default: 401
        title:
          type: string
          default: "Access denied."
    Forbidden:
      type: object
      description: "Forbidden access."
      properties:
        status:
          type: integer
          default: 403
        title:
          type: string
          default: "Forbidden access. Insufficient rights."
    InternalError:
      type: object
      description: "Internal error occurred."
      properties:
        status:
          type: integer
          default: 500
        title:
          type: string
          default: "Internal error occurred."
    NotSupported:
      type: object
      description: "Version not supported."
      properties:
        status:
          type: integer
          default: 402
        title:
          type: string
          default: "You are using unsupported version of this app."
