openapi: 3.0.3
info:
  title: Intune Adapter
  description: Web application that will serve as verification steps using Azrure AD
  version: 3.0.0
servers:
  - url:  https://testco-app.azurewebsites.net

tags:
  - name: Verify
    description: Endpoint for verifying client
  - name: Upload file
    description: Endpoint for checking / receiveing of payload sent by the client
  - name: Version check
    description: Endpoint for verifying app's compatibility
  - name: BE version
    description: Public API of backend version

paths:

  /intune/version:
    get:
      tags:
        - BE version
      summary: "Public endpoint for checking backend's version."
      operationId: "getVersion"

      responses:
        200:
          $ref: '#/components/responses/Version'
        500:
          $ref: '#/components/responses/InternalError'


  /intune/version-check:
    get:
      tags:
        - Version check
      summary: "Verify client's app version."
      operationId: "appVersionCheck"
      parameters:
        - in: header
          name: X-UBS-APP-ENTITY
          schema:
            type: string
            required: true

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AppInformation'
      responses:
        200:
          $ref: '#/components/responses/Accepted'
        400:
          $ref: '#/components/responses/BadRequest'
        426:
          $ref: '#/components/responses/NotSupported'
        500:
          $ref: '#/components/responses/InternalError'

  /intune/verify:
    get:
      tags:
      - Verify
      summary: "Verify token provided by the client"
      operationId: "verify"

      security:
        - bearerAuth: [ ]

      responses:
        200:
          $ref: '#/components/responses/Accepted'
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/AccessDenied'
        403:
          $ref: '#/components/responses/ForbiddenAccess'
        500:
          $ref: '#/components/responses/InternalError'

  /intune/upload-file:
    post:
      tags:
        - Upload file
      summary: "Receive uploaded file from client"
      description: "Check the validity of the token and verify the uploaded file"
      operationId: "uploadFile"

      security:
        - bearerAuth: []

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FileUpload'

      responses:
        200:
          $ref: '#/components/responses/UploadSuccess'
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/AccessDenied'
        403:
          $ref: '#/components/responses/ForbiddenAccess'
        500:
          $ref: '#/components/responses/InternalError'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    Version:
      description: "Version of the backend application."
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AppVersion'

    Accepted:
      description: "Access granted."
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Accepted'

    UploadSuccess:
      description: "Upload success."
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UploadSuccess'

    BadRequest:
      description: "Request error."
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BadRequest'

    AccessDenied:
      description: "Access denied."
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AccessDenied'

    ForbiddenAccess:
      description: "Access forbidden. Not enough rights."
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Forbidden'

    InternalError:
      description: "Internal Error occured."
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InternalError'

  schemas:
    AppVersion:
      type: object
      description: "Version of the BE application."
      properties:
        version:
          type: string
          example: "3.0.0"

    AppInformation:
      type: object
      description: "Information about request origin."
      required:
        - appOs
        - appVersion
      properties:
        appOs:
          type: string
          example: "iOs"
        appVersion:
          type: string
          example: "2.0.0"

    FileUpload:
      type: object
      description: "Uploaded file"
      required:
        - file
        - metadata
      properties:
        file:
          type: string
          example: "byte64encodedString"
        metadata:
          $ref: '#/components/schemas/Metadata'
    Metadata:
      type: object
      description: "Information about the file sent"
      properties:
        businessDomain:
          type: string
          example: "WM"
        documentDomain:
          type: string
          example: "011"
        copyOfOriginal:
          type: boolean
          default: false
        country:
          type: string
          default: ph
        copies:
          type: array
          items:
            type: object
            properties:
              relationNumber:
                type: string
                example: 001
              directProcessing:
                type: boolean
                default: false

    Accepted:
      type: object
      description: "Accepted"
      properties:
          status:
            type: integer
            example: 200
            default: 200
          title:
            type: string
            example: "Access granted"
            default: "Access granted"

    UploadSuccess:
      type: object
      description: "Uploaded successfully."
      properties:
        status:
          type: integer
          example: 200
          default: 200
        title:
          type: string
          example: "File uploaded successfully."
          default: "File uploaded successfully."
    BadRequest:
      type: object
      description: "Something wrong with the request."
      properties:
        status:
          type: integer
          default: 400
        title:
          type: string
          default: "Bad Request."
    AccessDenied:
      type: object
      description: "Access denied."
      properties:
        status:
          type: integer
          default: 401
        title:
          type: string
          default: "Access denied."
    Forbidden:
      type: object
      description: "Forbidden access."
      properties:
        status:
          type: integer
          default: 403
        title:
          type: string
          default: "Forbidden access. Insufficient rights."
    InternalError:
      type: object
      description: "Internal error occurred."
      properties:
        status:
          type: integer
          default: 500
        title:
          type: string
          default: "Internal error occurred."
    NotSupported:
      type: object
      description: "Version not supported."
      properties:
        status:
          type: integer
          default: 402
        title:
          type: string
          default: "Version compatibility error."
