openapi: 3.0.3
info:
  title: Web App API
  description: Web App API
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /verify:
    get:
      summary: "Verify token provided by the client"
      operationId: "verify"
      responses:
        200:
        400:
        401:
        403:
        500:

components:
  schemas:
    responseSchema:
      type: object
      description: "Response object"
      properties:
        status:
          type: integer
          example: 200
          default: 200
        title:
          type: string
          example: "Access granted"
          default: "Access granted"
  responses:
    Accepted:
      description: "Access granted."
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/responseSchema'