openapi: 3.0.3
info:
  title: Web App API
  description: Web App API
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /verify:
    get:
      summary: "Verify token provided by the client"
      operationId: "verify"
      responses:
        200:
          $ref: '#/components/responses/Accepted'
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          description: "Access denied."
        403:
          description: "Insufficient rights. You are not allowed to call this service."
        500:
          description: "Internal error."

components:
  responses:
    Accepted:
      description: "Access granted."
      content:
        application/json:
          schema:
            type: object
            description: ""
            properties:
              status:
                type: integer
                example: 200
                default: 200
              title:
                type: string
                example: "Access granted"
                default: "Access granted"

    BadRequest:
      description: "Request error."
      content:
        application/json:
          schema:
            type: object
            description: ""
            properties:
              status:
                type: integer
                default: 400
              title:
                type: string
                default: "Bad Request."